[package]
name = "crate_b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crate_c = { path = "../crate_c", features =  [ "feat" ] }
